# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI for Unit Tests

on: [push, pull_request]

jobs:
  build:
    env:
      NNG_VERSION: 1.8.0
    runs-on: ubuntu-latest

    steps:
    - name: apt-update
      run: sudo apt-get update

    - name: install cmake and ninja
      run: sudo apt-get install cmake ninja-build

    - name: install mbedTLS
      run: sudo apt-get install libmbedtls-dev

    - name: fetch nng v1.8.0
      run: wget "https://github.com/nanomsg/nng/archive/v${NNG_VERSION}.tar.gz"

    - name: unpack nng
      run: tar xvfz "v${NNG_VERSION}.tar.gz"

    - name: make nng build dir
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: configure cmake
      working-directory: ${{github.workspace}}/build
      run: cmake "${GITHUB_WORKSPACE}/nng-${NNG_VERSION}" -DBUILD_SHARED_LIBS=yes -DNNG_ENABLE_TLS=ON -G Ninja

    - name: configure cache of nng build
      id: cache-nng
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/build
        key: ${{ runner.os }}-nng

    - name: build nng
      working-directory: ${{github.workspace}}/build
      run: ninja

    - name: install nng
      working-directory: ${{github.workspace}}/build
      run: sudo ninja install

    - name: update ldconfig
      run: sudo ldconfig

    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Test with Gradle
      run: ./gradlew test
